let a=10;
let b=20;
console.log("Arithmetic Operators:");
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);
console.log(a**b);
let x=10;
let y=20;
console.log("Comparison Operators:");
console.log(x==y);
console.log(x!=y);
// logical Operator 
let q=2;
let r='2';
console.log("Equal with type coercion",q==r);
console.log("Strict equal",q===r);
console.log("Not equal",q!=r);
console.log("Strict not equal",q!==r);
console.log("Greaterthan",q>r);
console.log("Lessthan",q<r);
console.log("Greaterthen or equals to",q>=r);
console.log("Lessthen or equals to",q<=r);
console.log("AND",q>5 && r< 10);
console.log("OR",q>5 || r< 10);
console.log("NOR",!(q>5));
console.log(typeof a);
console.log(typeof b);
console.log(typeof x);
console.log(typeof y);
